### ISSUE TITLE
how to use your code

### ISSUE THREAD

**Issue by 11lucky111** [AirGuanZ/ImageQuilting#1]
I can't use your code in my computer.Can you tell me how to use it?

**Comment by AirGuanZ** [comment]
Hi,
The only requirements of these codes are cmake and a c++17-compatible compiler. Could you please describe the problem you encountered in more detail?

**Comment by 11lucky111** [comment]
Thank you!I have solved the problem.Your code is very nice!------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月6日(星期二) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AirGuanZ/ImageQuilting] how to use your code (#1)
