### ISSUE TITLE
‘T’ was not declared in this scope

### ISSUE THREAD

**Issue by Wuwenll** [AirGuanZ/ImageQuilting#2]
In file included from /home/wwl/data/ImageQuilting/lib/agz-utils/include/agz/utility/math/decl/tensor.h:6:0,
                 from /home/wwl/data/ImageQuilting/lib/agz-utils/include/agz/utility/math/math.h:17,
                 from /home/wwl/data/ImageQuilting/lib/agz-utils/include/agz/utility/math.h:3,
                 from /home/wwl/data/ImageQuilting/lib/agz-utils/include/agz/utility/image/load_image.h:5,
                 from /home/wwl/data/ImageQuilting/lib/agz-utils/src/image/load_image.cpp:6:
/home/wwl/data/ImageQuilting/lib/agz-utils/include/agz/utility/math/decl/tensor_view.h:42:32: error: ‘T’ was not declared in this scope
                 std::is_same_v<T, U> && CONST_TENSOR && !CONST2>>

Hello, I encountered this problem when I "make". May I ask which step I went wrong?

**Comment by AirGuanZ** [comment]
Fixed. Thanks for reporting this!

**Comment by Wuwenll** [comment]
Scanning dependencies of target AGZUtils
[  1%] Building CXX object lib/agz-utils/CMakeFiles/AGZUtils.dir/src/graphics_api/gl/immediate2d.cpp.o
[  2%] Building CXX object lib/agz-utils/CMakeFiles/AGZUtils.dir/src/mesh/load_mesh.cpp.o
In file included from /home/wwl/data/ImageQuilting/lib/agz-utils/include/agz-utils/file.h:3:0,
                 from /home/wwl/data/ImageQuilting/lib/agz-utils/src/mesh/load_mesh.cpp:1:
/home/wwl/data/ImageQuilting/lib/agz-utils/include/agz-utils/file/dir.h:3:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.

Hello i have a new problem，filesystem: No such file or directory. I tried to use these to solve this problem.
#include <experimental/filesystem>
std::experimental::filesystem; 
But there will be new problems：
Scanning dependencies of target ImageQuilting
[ 97%] Building CXX object CMakeFiles/ImageQuilting.dir/src/main.cpp.o
[ 98%] Linking CXX executable ImageQuilting
CMakeFiles/ImageQuilting.dir/src/main.cpp.o: In function `run(int, char**)':
main.cpp:(.text+0x3215): undefined reference to `std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'
CMakeFiles/ImageQuilting.dir/src/main.cpp.o: In function `agz::file::create_directory_for_file(std::experimental::filesystem::v1::__cxx11::path const&)':
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE]+0x38): undefined reference to `std::experimental::filesystem::v1::current_path[abi:cxx11]()'
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE]+0x46): undefined reference to `std::experimental::filesystem::v1::absolute(std::experimental::filesystem::v1::__cxx11::path const&, std::experimental::filesystem::v1::__cxx11::path const&)'
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE]+0x56): undefined reference to `std::experimental::filesystem::v1::__cxx11::path::has_parent_path() const'
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE]+0x65): undefined reference to `std::experimental::filesystem::v1::__cxx11::path::parent_path() const'
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE]+0x6d): undefined reference to `std::experimental::filesystem::v1::status(std::experimental::filesystem::v1::__cxx11::path const&)'
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE]+0x7c): undefined reference to `std::experimental::filesystem::v1::create_directories(std::experimental::filesystem::v1::__cxx11::path const&)'
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt12experimental10filesystem2v17__cxx114pathE]+0xd9): undefined reference to `std::experimental::filesystem::v1::status(std::experimental::filesystem::v1::__cxx11::path const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/ImageQuilting.dir/build.make:99: recipe for target 'ImageQuilting' failed
make[2]: *** [ImageQuilting] Error 1
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/ImageQuilting.dir/all' failed
make[1]: *** [CMakeFiles/ImageQuilting.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I am a novice, can you help me see what the problem is? Thinks

**Comment by AirGuanZ** [comment]
That looks like a compiler environment problem. `std::filesystem` requires a C++17-compatible compiler while early versions of g++/clang++ require specific link flags to work with `filesystem`. Could you please tell me your compiler version?

**Comment by Wuwenll** [comment]
You are right! After I just updated gcc, the previous problem has been solved. This is the previous version of the compiler. 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.4.0-1ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04)

But I encountered a new problem


[ 97%] Building CXX object CMakeFiles/ImageQuilting.dir/src/imageQuilting.cpp.o
/home/wwl/data/ImageQuilting/src/imageQuilting.cpp: In member function ‘ImageView<agz::math::_simd_float3_t> ImageQuilting::pickSourceBlock(Image<agz::math::_simd_float3_t>&, Image<agz::math::_simd_float3_t>&, int, int, std::default_random_engine&) const’:
/home/wwl/data/ImageQuilting/src/imageQuilting.cpp:377:34: error: no match for call to ‘(const std::uniform_int_distribution<int>) (std::default_random_engine&)’
         const int srcX = disX(rng);
                                  ^
In file included from /usr/include/c++/8/bits/stl_algo.h:66,
                 from /usr/include/c++/8/functional:65,
                 from /home/wwl/data/ImageQuilting/lib/agz-utils/include/agz-utils/misc/hash.h:3,
                 from /home/wwl/data/ImageQuilting/lib/agz-utils/include/agz-utils/misc.h:10,
                 from /home/wwl/data/ImageQuilting/src/imageQuilting.cpp:4:
/usr/include/c++/8/bits/uniform_int_dist.h:165:2: note: candidate: ‘std::uniform_int_distribution<_IntType>::result_type std::uniform_int_distribution<_IntType>::operator()(_UniformRandomNumberGenerator&) [with _UniformRandomNumberGenerator = std::linear_congruential_engine<long unsigned int, 16807, 0, 2147483647>; _IntType = int; std::uniform_int_distribution<_IntType>::result_type = int]’ <near match>
  operator()(_UniformRandomNumberGenerator& __urng)
  ^~~~~~~~
/usr/include/c++/8/bits/uniform_int_dist.h:165:2: note:   passing ‘const std::uniform_int_distribution<int>*’ as ‘this’ argument discards qualifiers
/usr/include/c++/8/bits/uniform_int_dist.h:170:2: note: candidate: ‘template<class _UniformRandomNumberGenerator> std::uniform_int_distribution<_IntType>::result_type std::uniform_int_distribution<_IntType>::operator()(_UniformRandomNumberGenerator&, const std::uniform_int_distribution<_IntType>::param_type&) [with _UniformRandomNumberGenerator = _UniformRandomNumberGenerator; _IntType = int]’
  operator()(_UniformRandomNumberGenerator& __urng,
  ^~~~~~~~
/usr/include/c++/8/bits/uniform_int_dist.h:170:2: note:   template argument deduction/substitution failed:
/home/wwl/data/ImageQuilting/src/imageQuilting.cpp:377:34: note:   candidate expects 2 arguments, 1 provided
         const int srcX = disX(rng);
                                  ^
/home/wwl/data/ImageQuilting/src/imageQuilting.cpp:378:34: error: no match for call to ‘(const std::uniform_int_distribution<int>) (std::default_random_engine&)’
         const int srcY = disY(rng);
                                  ^
In file included from /usr/include/c++/8/bits/stl_algo.h:66,
                 from /usr/include/c++/8/functional:65,
                 from /home/wwl/data/ImageQuilting/lib/agz-utils/include/agz-utils/misc/hash.h:3,
                 from /home/wwl/data/ImageQuilting/lib/agz-utils/include/agz-utils/misc.h:10,
                 from /home/wwl/data/ImageQuilting/src/imageQuilting.cpp:4:
/usr/include/c++/8/bits/uniform_int_dist.h:165:2: note: candidate: ‘std::uniform_int_distribution<_IntType>::result_type std::uniform_int_distribution<_IntType>::operator()(_UniformRandomNumberGenerator&) [with _UniformRandomNumberGenerator = std::linear_congruential_engine<long unsigned int, 16807, 0, 2147483647>; _IntType = int; std::uniform_int_distribution<_IntType>::result_type = int]’ <near match>
  operator()(_UniformRandomNumberGenerator& __urng)
  ^~~~~~~~
/usr/include/c++/8/bits/uniform_int_dist.h:165:2: note:   passing ‘const std::uniform_int_distribution<int>*’ as ‘this’ argument discards qualifiers
/usr/include/c++/8/bits/uniform_int_dist.h:170:2: note: candidate: ‘template<class _UniformRandomNumberGenerator> std::uniform_int_distribution<_IntType>::result_type std::uniform_int_distribution<_IntType>::operator()(_UniformRandomNumberGenerator&, const std::uniform_int_distribution<_IntType>::param_type&) [with _UniformRandomNumberGenerator = _UniformRandomNumberGenerator; _IntType = int]’
  operator()(_UniformRandomNumberGenerator& __urng,
  ^~~~~~~~
/usr/include/c++/8/bits/uniform_int_dist.h:170:2: note:   template argument deduction/substitution failed:
/home/wwl/data/ImageQuilting/src/imageQuilting.cpp:378:34: note:   candidate expects 2 arguments, 1 provided
         const int srcY = disY(rng);
                                  ^
/home/wwl/data/ImageQuilting/src/imageQuilting.cpp:411:39: error: no match for call to ‘(const std::uniform_int_distribution<int>) (std::default_random_engine&)’
     const auto xy = allowedXYs[dis(rng)];
                                       ^
In file included from /usr/include/c++/8/bits/stl_algo.h:66,
                 from /usr/include/c++/8/functional:65,
                 from /home/wwl/data/ImageQuilting/lib/agz-utils/include/agz-utils/misc/hash.h:3,
                 from /home/wwl/data/ImageQuilting/lib/agz-utils/include/agz-utils/misc.h:10,
                 from /home/wwl/data/ImageQuilting/src/imageQuilting.cpp:4:
/usr/include/c++/8/bits/uniform_int_dist.h:165:2: note: candidate: ‘std::uniform_int_distribution<_IntType>::result_type std::uniform_int_distribution<_IntType>::operator()(_UniformRandomNumberGenerator&) [with _UniformRandomNumberGenerator = std::linear_congruential_engine<long unsigned int, 16807, 0, 2147483647>; _IntType = int; std::uniform_int_distribution<_IntType>::result_type = int]’ <near match>
  operator()(_UniformRandomNumberGenerator& __urng)
  ^~~~~~~~
/usr/include/c++/8/bits/uniform_int_dist.h:165:2: note:   passing ‘const std::uniform_int_distribution<int>*’ as ‘this’ argument discards qualifiers
/usr/include/c++/8/bits/uniform_int_dist.h:170:2: note: candidate: ‘template<class _UniformRandomNumberGenerator> std::uniform_int_distribution<_IntType>::result_type std::uniform_int_distribution<_IntType>::operator()(_UniformRandomNumberGenerator&, const std::uniform_int_distribution<_IntType>::param_type&) [with _UniformRandomNumberGenerator = _UniformRandomNumberGenerator; _IntType = int]’
  operator()(_UniformRandomNumberGenerator& __urng,
  ^~~~~~~~
/usr/include/c++/8/bits/uniform_int_dist.h:170:2: note:   template argument deduction/substitution failed:
/home/wwl/data/ImageQuilting/src/imageQuilting.cpp:411:39: note:   candidate expects 2 arguments, 1 provided
     const auto xy = allowedXYs[dis(rng)];
                                       ^
CMakeFiles/ImageQuilting.dir/build.make:62: recipe for target 'CMakeFiles/ImageQuilting.dir/src/imageQuilting.cpp.o' failed
make[2]: *** [CMakeFiles/ImageQuilting.dir/src/imageQuilting.cpp.o] Error 1
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/ImageQuilting.dir/all' failed
make[1]: *** [CMakeFiles/ImageQuilting.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AirGuanZ** [comment]
Fixed. Please try the new version.

**Comment by Wuwenll** [comment]
I have updated the code, but there are still problems.

CMakeFiles/ImageQuilting.dir/src/main.cpp.o: In function `run(int, char**)':
main.cpp:(.text+0x3160): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
CMakeFiles/ImageQuilting.dir/src/main.cpp.o: In function `agz::file::create_directory_for_file(std::filesystem::__cxx11::path const&)':
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE]+0x30): undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE]+0x38): undefined reference to `std::filesystem::__cxx11::path::has_parent_path() const'
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE]+0x53): undefined reference to `std::filesystem::__cxx11::path::parent_path() const'
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE]+0x5b): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE]+0x6e): undefined reference to `std::filesystem::create_directories(std::filesystem::__cxx11::path const&)'
main.cpp:(.text._ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE[_ZN3agz4file25create_directory_for_fileERKNSt10filesystem7__cxx114pathE]+0x151): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/ImageQuilting.dir/build.make:99: recipe for target 'ImageQuilting' failed
make[2]: *** [ImageQuilting] Error 1
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/ImageQuilting.dir/all' failed
make[1]: *** [CMakeFiles/ImageQuilting.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AirGuanZ** [comment]
This is still an environmental problem. Try adding link flag `-lstdc++fs`.
